# Generated by Django 5.2.5 on 2025-08-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_category_contextentry_task_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.DeleteModel(
            name='ContextEntry',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority_score',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
